version: '3.4'

services:
  taskopia:
    image: ${DOCKER_REGISTRY-}taskopia
    container_name: taskopia.api
    build:
      context: .
      dockerfile: Taskopia/Dockerfile
    ports:
     -  9000:8080
     -  9001:8081
    depends_on:
    - taskopia.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  taskopia.db:
   image: postgres
   container_name: taskopia.db
   environment:
     POSTGRES_DB: taskopia
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
   volumes:
     - ./.containers/taskopia-db:/var/lib/postgresql/data 
   ports:
     - 15432:5432 
   





